//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class UserInfo
{
    public int uPk { get; set; }
    public string uID { get; set; }
    public string uName { get; set; }
    public string uPwd { get; set; }
    public int uisdelete { get; set; }
    public System.DateTime CreateTime { get; set; }
}
